---
- hosts: nginx_nodes
  become: yes
  tags: [nginx]
  roles:
    - nginx
    - telegraf

- hosts: app_nodes
  become: yes
  tags: [app]
  roles:
    - telegraf
    - app

- hosts: db_nodes
  become: yes
  tags: [db]
  roles:
    - telegraf
    - database

- hosts: stats_server
  become: yes
  tags: [grafana]
  vars:
    metrics_database_name: "metrics"
    metrics_database_password: "metrics"
    metrics_database_user: "metrics"
    datasource_name: "my-influx"
    grafana_http_port: 3000
    telegraf_config_path: "telegraf_default.conf"
  roles:
    - influxdb
    - grafana
  tasks:
    - include_tasks: tasks/configure-grafana.yml
